<a href="https://colab.research.google.com/github/studiousdoston/AI-Foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
print(pd.__version__)

2.2.3

In [ ]:
import pandas as pd
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Toyota", "Merc", "Kia"],
  'ratings': [8, 7, 6, 8, 7, 6]
}

df = pd.DataFrame(mydataset)
print(pd.DataFrame(df))

     cars  ratings
0     BMW        8
1   Volvo        7
2    Ford        6
3  Toyota        8
4    Merc        7
5     Kia        6

In [ ]:
df.head() # default 5 rows from the top

     cars  ratings
0     BMW        8
1   Volvo        7
2    Ford        6
3  Toyota        8
4    Merc        7

In [ ]:
df.tail() # default 5 rows from the bottom.

     cars  ratings
1   Volvo        7
2    Ford        6
3  Toyota        8
4    Merc        7
5     Kia        6

In [ ]:
df.shape

(6, 2)

In [ ]:
df.columns

Index(['cars', 'ratings'], dtype='object')

In [ ]:
df.dtypes

cars       object
ratings     int64
dtype: object

In [ ]:
df.describe()

        ratings
count  6.000000
mean   7.000000
std    0.894427
min    6.000000
25%    6.250000
50%    7.000000
75%    7.750000
max    8.000000

In [ ]:
df.iloc[0:3]

    cars  ratings
0    BMW        8
1  Volvo        7
2   Ford        6

In [ ]:
df.loc[:, 'cars']

0    8
1    7
2    6
3    8
4    7
5    6
Name: ratings, dtype: int64

In [ ]:
print(df)

     cars  ratings
0     BMW        8
1   Volvo        7
2    Ford        6
3  Toyota        8
4    Merc        7
5     Kia        6

In [ ]:
df[df['ratings'] > 6]

     cars  ratings
0     BMW        8
1   Volvo        7
3  Toyota        8
4    Merc        7

In [ ]:
df.mean(numeric_only=True)

ratings    7.0
dtype: float64

In [ ]:
df["ratings"].sum()

np.int64(42)

In [ ]:
df.min()
# df.max()

cars       BMW
ratings      6
dtype: object

In [ ]:
df.median(numeric_only=True)

ratings    7.0
dtype: float64

In [ ]:
df.count()

cars       6
ratings    6
dtype: int64

In [ ]:
df.std(numeric_only=True)

ratings    0.894427
dtype: float64

In [ ]:
data_with_missing = {
  'cars': ["BMW", "Volvo", None, "Toyota", "Merc", "Kia"],
  'ratings': [8, 7, 6, None, 7, 6]
}
df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

     cars  ratings
0     BMW      8.0
1   Volvo      7.0
2    None      6.0
3  Toyota      NaN
4    Merc      7.0
5     Kia      6.0

In [ ]:
df_missing.isnull().sum()

cars       1
ratings    1
dtype: int64

In [ ]:
df_missing.dropna()

    cars  ratings
0    BMW      8.0
1  Volvo      7.0
4   Merc      7.0
5    Kia      6.0

In [ ]:
df_missing.dropna(subset=['cars'])

     cars  ratings
0     BMW      8.0
1   Volvo      7.0
3  Toyota      NaN
4    Merc      7.0
5     Kia      6.0

In [ ]:
df_missing.fillna({"cars": "unknown", "ratings": 0})

      cars  ratings
0      BMW      8.0
1    Volvo      7.0
2  unknown      6.0
3   Toyota      0.0
4     Merc      7.0
5      Kia      6.0

In [3]:
import pandas as pd
df = pd.read_csv("Titanic-Dataset.csv")
df.tail()

# df = pd.read_excel("filename.xlsx")
# df = pd.read_json("filename.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [7]:
df.to_json("Titanic-Dataset.json")

In [9]:
# Series => 1D
fruits = pd.Series(['apple', 'cherry', 'banana'])
print(fruits)

0     apple
1    cherry
2    banana
dtype: object